name: Deploy to AWS Fargate

on:
  push:
    branches:
      - master  # Trigger the action on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_NAME }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}  # Correct ECS Cluster Name
      ECS_SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}  # Correct ECS Service Name
      TASK_DEFINITION_NAME: ${{ secrets.TASK_DEFINITION_NAME }}  # Task Definition Family Name (without revision)
      TASK_ROLE: ${{ secrets.TASK_ROLE }}  # Task Role ARN
      TASK_EXECUTION_ROLE: ${{ secrets.TASK_EXECUTION_ROLE }}  # Task Execution Role ARN

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get latest task definition revision
      id: get-task-definition
      run: |
        LATEST_TASK_DEF_ARN=$(aws ecs describe-task-definition \
          --task-definition $TASK_DEFINITION_NAME \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        echo "TASK_DEF_ARN=$LATEST_TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Update ECS service with new task definition
      run: |
        aws ecs update-service \
          --cluster $CLUSTER_NAME \
          --service $ECS_SERVICE_NAME \
          --task-definition $TASK_DEF_ARN \
          --role $TASK_ROLE \
          --execution-role $TASK_EXECUTION_ROLE \
          --region ${{ secrets.AWS_REGION }}

    - name: Wait for ECS service to stabilize
      run: |
        aws ecs wait services-stable \
          --cluster $CLUSTER_NAME \
          --services $ECS_SERVICE_NAME \
          --region ${{ secrets.AWS_REGION }}

    - name: Fetch logs from CloudWatch for ECS task
      run: |
        LOG_STREAM=$(aws logs describe-log-streams \
          --log-group-name /ecs/$ECS_SERVICE_NAME \
          --order-by "LastEventTime" \
          --limit 1 \
          --query "logStreams[0].logStreamName" \
          --output text)
        
        aws logs get-log-events \
          --log-group-name /ecs/$ECS_SERVICE_NAME \
          --log-stream-name $LOG_STREAM \
          --limit 10 \
          --query "events[*].message" \
          --output text
