name: Deploy to AWS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  ECS_SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
  TASK_DEFINITION_NAME: ${{ secrets.TASK_DEFINITION_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  TASK_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/VenlinkFargateRole"
  EXECUTION_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole"

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch latest task definition
        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION_NAME --region $AWS_REGION > task-def.json

      - name: Register new task definition with updated roles
        id: register-task-def
        run: |
          NEW_TASK_DEF=$(jq '.taskDefinition | 
            del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .requiresAttributes, .compatibilities) |
            .taskRoleArn = env.TASK_ROLE_ARN | 
            .executionRoleArn = env.EXECUTION_ROLE_ARN' task-def.json)

          echo "$NEW_TASK_DEF" > new-task-def.json

          REGISTERED_TASK_DEF=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json)
          TASK_DEF_ARN=$(echo "$REGISTERED_TASK_DEF" | jq -r '.taskDefinition.taskDefinitionArn')

          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS Service to use new task definition
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $TASK_DEF_ARN --region $AWS_REGION
