name: Deploy to AWS Fargate

on:
  push:
    branches:
      - master

env:
  CONTAINER_NAME: "containervenlink"  # Defined once at workflow level
  ECR_REPOSITORY: "venlink"          # ECR repository name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ env.CONTAINER_NAME }} .

    - name: Tag Docker image
      run: |
        docker tag ${{ env.CONTAINER_NAME }}:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      ECS_SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
      TASK_DEFINITION_NAME: ${{ secrets.TASK_DEFINITION_NAME }}
      TASK_ROLE_ARN: ${{ secrets.TASK_ROLE }}
      TASK_EXECUTION_ROLE_ARN: ${{ secrets.TASK_EXECUTION_ROLE }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sanitize service name
      run: |
        ECS_SERVICE_NAME_CLEAN=$(echo "$ECS_SERVICE_NAME" | tr ' ' '-' | tr '/' '-' | tr '_' '-')
        echo "ECS_SERVICE_NAME_CLEAN=$ECS_SERVICE_NAME_CLEAN" >> $GITHUB_ENV

    - name: Register new task definition
      run: |
        aws ecs register-task-definition \
          --family $TASK_DEFINITION_NAME \
          --execution-role-arn $TASK_EXECUTION_ROLE_ARN \
          --task-role-arn $TASK_ROLE_ARN \
          --network-mode awsvpc \
          --cpu 256 \
          --memory 512 \
          --requires-compatibilities FARGATE \
          --container-definitions "$(jq -n \
            --arg image "${{ env.IMAGE_URI }}" \
            --arg name "${{ env.CONTAINER_NAME }}" \
            --arg region "${{ secrets.AWS_REGION }}" \
            --arg log_group "/ecs/$ECS_SERVICE_NAME_CLEAN" \
            '{
              "name": $name,
              "image": $image,
              "essential": true,
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": $log_group,
                  "awslogs-region": $region,
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }')"

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster $CLUSTER_NAME \
          --service $ECS_SERVICE_NAME_CLEAN \
          --task-definition $TASK_DEFINITION_NAME \
          --force-new-deployment

    - name: Verify deployment
      run: |
        aws ecs wait services-stable \
          --cluster $CLUSTER_NAME \
          --services $ECS_SERVICE_NAME_CLEAN
